declare const openGridThemeTokens: {
    readonly fontFamily: "--og-font-family";
    readonly fontSize: "--og-font-size";
    readonly fontWeightMedium: "--og-font-weight-medium";
    readonly fontWeightSemibold: "--og-font-weight-semibold";
    readonly borderColor: "--og-border-color";
    readonly border: "--og-border";
    readonly borderSubtle: "--og-border-subtle";
    readonly borderStrong: "--og-border-strong";
    readonly surface: "--og-surface";
    readonly surfaceRaised: "--og-surface-raised";
    readonly surfaceMuted: "--og-surface-muted";
    readonly surfaceSubtle: "--og-surface-subtle";
    readonly surfaceHover: "--og-surface-hover";
    readonly surfaceSelected: "--og-surface-selected";
    readonly text: "--og-text";
    readonly textMuted: "--og-text-muted";
    readonly textSubtle: "--og-text-subtle";
    readonly accent: "--og-accent";
    readonly accentHover: "--og-accent-hover";
    readonly accentSoft: "--og-accent-soft";
    readonly focus: "--og-focus";
    readonly danger: "--og-danger";
    readonly dangerSoft: "--og-danger-soft";
    readonly rowHeight: "--og-row-height";
    readonly headerHeight: "--og-header-height";
    readonly controlHeight: "--og-control-height";
    readonly radiusSmall: "--og-radius-sm";
    readonly radius: "--og-radius";
    readonly radiusLarge: "--og-radius-lg";
    readonly shadowSmall: "--og-shadow-sm";
    readonly shadowMedium: "--og-shadow-md";
    readonly shadowPinnedLeft: "--og-shadow-pinned-left";
    readonly shadowPinnedRight: "--og-shadow-pinned-right";
    readonly transition: "--og-transition";
};
type OpenGridThemeToken = keyof typeof openGridThemeTokens;
type OpenGridTheme = Partial<Record<OpenGridThemeToken, string>>;
type OpenGridThemeCustomProperty = (typeof openGridThemeTokens)[OpenGridThemeToken];
type OpenGridThemeStyle = Partial<Record<OpenGridThemeCustomProperty, string>>;
declare function createOpenGridThemeStyle(theme: OpenGridTheme): OpenGridThemeStyle;
declare function createOpenGridThemeCssText(theme: OpenGridTheme): string;

export { type OpenGridTheme, type OpenGridThemeCustomProperty, type OpenGridThemeStyle, type OpenGridThemeToken, createOpenGridThemeCssText, createOpenGridThemeStyle, openGridThemeTokens };
