import type { ExportFile } from "@open-grid/core";
import { downloadBrowserExportFile } from "@open-grid/primitives";

export { default as DataGrid } from "./DataGrid.svelte";
export type {
  ColumnVirtualizationOptions,
  DataGridProps,
  GridReadyHandler,
  HeaderActionMenuActionItem,
  HeaderActionMenuContext,
  HeaderActionMenuCustomItem,
  HeaderActionMenuItem,
  HeaderActionMenuItems,
  HeaderActionMenuLabelItem,
  HeaderActionMenuSeparatorItem,
  RowVirtualizationOptions,
} from "./DataGrid.svelte";
export { createColumnHelper, createGridStore, fitColumnsToWidth } from "@open-grid/svelte";
export {
  GRID_PREFERENCES_VERSION,
  createGridPreferences,
  getBrowserGridPreferencesStorage,
  parseGridPreferences,
  readGridPreferences,
  removeGridPreferences,
  serializeGridPreferences,
  writeGridPreferences,
} from "@open-grid/primitives";
export type { GridDensity, GridPreferences, GridPreferencesOptions, GridPreferencesState, GridPreferencesStorageEnvironmentLike, GridPreferencesStorageLike } from "@open-grid/primitives";

export function downloadExportFile(file: ExportFile): boolean {
  return downloadBrowserExportFile(file);
}

export type {
  AccessorKey,
  AccessorColumnOptions,
  AccessorFnColumnDef,
  AccessorKeyColumnDef,
  AnyColumnDef,
  CellContext,
  CellCoordinate,
  CellEditEvent,
  CellEditEventParams,
  CellEditHistoryAction,
  CellEditHistoryState,
  CellEditOption,
  CellEditPhase,
  CellEditParserContext,
  CellEditValidationContext,
  CellEditValidationResult,
  CellEditValidationState,
  CellEditingState,
  CellFillOptions,
  CellInteractionEvent,
  CellInteractionEventParams,
  CellRange,
  CellRangeSelectionState,
  ClipboardCellContext,
  ClipboardCopyOptions,
  ClipboardPasteCellContext,
  ClipboardPasteCommittedCell,
  ClipboardPasteOptions,
  ClipboardPasteResult,
  ClipboardPasteSkippedCell,
  ClipboardPasteSkippedReason,
  ClipboardPasteValidationError,
  Column,
  ColumnDef,
  ColumnHelper,
  ColumnFilter,
  ColumnFiltersState,
  ColumnId,
  ColumnMovePosition,
  ColumnOrderState,
  ColumnPinningPosition,
  ColumnPinningState,
  ColumnResizeEvent,
  ColumnResizeEventParams,
  ColumnResizePhase,
  ColumnSizingState,
  ColumnVisibilityState,
  DisplayColumnDef,
  ExportFile,
  ExportFileOptions,
  ExpandedState,
  FitColumnsToWidthOptions,
  FilterFn,
  Grid,
  GridCacheDiagnostics,
  GridCacheDiagnosticsEntry,
  GridCacheKey,
  GridOptions,
  GridState,
  GroupingState,
  Header,
  HeaderGroup,
  GroupColumnDef,
  HeaderContext,
  MoveFocusOptions,
  PaginationState,
  Row,
  RowId,
  RowInteractionEvent,
  RowInteractionEventParams,
  RowModel,
  RowSelectionCleanupScope,
  RowSelectionState,
  SortFn,
  SortingRule,
  SortingState,
  Updater,
} from "@open-grid/core";
